workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_id_login  # We'll set this in Codemagic Teams
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - nvsands127@gmail.com  # Your email for build notifications